linter:
  rules:
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_foreach
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - slash_for_doc_comments