name: nick_ops
description: Nick
version: 0.0.1
author: Nick Anderssohn <nicholas.anderssohn@outlook.com>
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  intl: 0.15.7
dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0