// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Upload.Db.EntityFramework;

namespace server.Migrations
{
    [DbContext(typeof(FullShareContext))]
    [Migration("20181029040040_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("server.Upload.Db.EntityFramework.Model.Files", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasMaxLength(36);

                    b.Property<long?>("Filesize")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("filesize")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("Uploadedon")
                        .HasColumnName("uploadedon");

                    b.HasKey("Code");

                    b.ToTable("files");
                });
#pragma warning restore 612, 618
        }
    }
}
