FROM nginx:1.15.4-alpine

COPY nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /full-share/download

RUN mkdir -p /etc/letsencrypt/live/nickanderssohn.com

COPY fullchain.pem /etc/letsencrypt/live/nickanderssohn.com/fullchain.pem
COPY privkey.pem /etc/letsencrypt/live/nickanderssohn.com/privkey.pem