name: full_share
description: Nick
version: 0.0.1
author: Nick Anderssohn <nicholas.anderssohn@outlook.com>
environment:
  sdk: any
dependencies:
  browser: any
  js: any
  dart_sass_transformer: any
transformers:
- $dart2js:
    minify: true
- dart_sass_transformer