name: cs451_team_project
description: Nick and Heidi's cs451 Project
version: 0.0.1
author: Nick Anderssohn <nicholas.anderssohn@wsu.edu>
environment:
  sdk: any
dependencies:
  browser: any
  js: any
  dart_sass_transformer: any
  protobuf: "^0.7.0"
  chartjs: "^0.4.0+1"
transformers:
- $dart2js:
    minify: true
- dart_sass_transformer